apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hospital-prod

resources:
  - namespace.yaml
  - ../../base

replicas:
  - name: fe-deployment-v1
    count: 3
  - name: be-deployment-v1
    count: 3

images:
  - name: 606030503959.dkr.ecr.us-east-1.amazonaws.com/ecr-fe
    newName: 606030503959.dkr.ecr.us-east-1.amazonaws.com/ecr-fe
    newTag: 4da0c2e3a1a4cc2ffdae6f67691bd43250b2bfc8
  - name: 606030503959.dkr.ecr.us-east-1.amazonaws.com/ecr-be
    newName: 606030503959.dkr.ecr.us-east-1.amazonaws.com/ecr-be
    newTag: 4da0c2e3a1a4cc2ffdae6f67691bd43250b2bfc8
